firstname = Magesh
lastname = palani
email = commissionarindia@gmail.com
password = mag123@
conformpass = mag123@
url = https://demowebshop.tricentis.com/
browser = chrome
invalidEmail = com@gmail.com
invalidPassword = jkdk27t
time = 30
