firstname = Magesh
lastname = palani
email = commissionarindia@gmail.com
password = mag123@
conformpass = mag123@
url = https://demowebshop.tricentis.com/
browser = chrome
invalidEmail = com@gmail.com
invalidPassword = jkdk27t
time = 30
newemail = commissionarindia005@gmailo.com
city = chennai
address = no 4 chennai
phnum = 9768866548
cardname = Magesh
cardnum = 98685443
code = 6312022